# Travis CI
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
 



sudo: required

before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev doxygen graphviz python3-sphinx
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
compiler:
  - gcc
  - clang

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - cmake CMakeLists.txt
  - make
  - make install
### install python package
  
