# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elenacuoco/develop/p4TSA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elenacuoco/develop/p4TSA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/data01/shared/TestEnvPy3.11/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elenacuoco/develop/p4TSA/CMakeFiles /home/elenacuoco/develop/p4TSA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elenacuoco/develop/p4TSA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named p4TSA

# Build rule for target.
p4TSA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p4TSA
.PHONY : p4TSA

# fast build rule for target.
p4TSA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/build
.PHONY : p4TSA/fast

src/AR2.o: src/AR2.cpp.o
.PHONY : src/AR2.o

# target to build an object file
src/AR2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2.cpp.o
.PHONY : src/AR2.cpp.o

src/AR2.i: src/AR2.cpp.i
.PHONY : src/AR2.i

# target to preprocess a source file
src/AR2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2.cpp.i
.PHONY : src/AR2.cpp.i

src/AR2.s: src/AR2.cpp.s
.PHONY : src/AR2.s

# target to generate assembly for a file
src/AR2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2.cpp.s
.PHONY : src/AR2.cpp.s

src/AR2Parcor.o: src/AR2Parcor.cpp.o
.PHONY : src/AR2Parcor.o

# target to build an object file
src/AR2Parcor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2Parcor.cpp.o
.PHONY : src/AR2Parcor.cpp.o

src/AR2Parcor.i: src/AR2Parcor.cpp.i
.PHONY : src/AR2Parcor.i

# target to preprocess a source file
src/AR2Parcor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2Parcor.cpp.i
.PHONY : src/AR2Parcor.cpp.i

src/AR2Parcor.s: src/AR2Parcor.cpp.s
.PHONY : src/AR2Parcor.s

# target to generate assembly for a file
src/AR2Parcor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/AR2Parcor.cpp.s
.PHONY : src/AR2Parcor.cpp.s

src/ARMAFilter.o: src/ARMAFilter.cpp.o
.PHONY : src/ARMAFilter.o

# target to build an object file
src/ARMAFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAFilter.cpp.o
.PHONY : src/ARMAFilter.cpp.o

src/ARMAFilter.i: src/ARMAFilter.cpp.i
.PHONY : src/ARMAFilter.i

# target to preprocess a source file
src/ARMAFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAFilter.cpp.i
.PHONY : src/ARMAFilter.cpp.i

src/ARMAFilter.s: src/ARMAFilter.cpp.s
.PHONY : src/ARMAFilter.s

# target to generate assembly for a file
src/ARMAFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAFilter.cpp.s
.PHONY : src/ARMAFilter.cpp.s

src/ARMAfit.o: src/ARMAfit.cpp.o
.PHONY : src/ARMAfit.o

# target to build an object file
src/ARMAfit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAfit.cpp.o
.PHONY : src/ARMAfit.cpp.o

src/ARMAfit.i: src/ARMAfit.cpp.i
.PHONY : src/ARMAfit.i

# target to preprocess a source file
src/ARMAfit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAfit.cpp.i
.PHONY : src/ARMAfit.cpp.i

src/ARMAfit.s: src/ARMAfit.cpp.s
.PHONY : src/ARMAfit.s

# target to generate assembly for a file
src/ARMAfit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ARMAfit.cpp.s
.PHONY : src/ARMAfit.cpp.s

src/ArBurgEstimator.o: src/ArBurgEstimator.cpp.o
.PHONY : src/ArBurgEstimator.o

# target to build an object file
src/ArBurgEstimator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArBurgEstimator.cpp.o
.PHONY : src/ArBurgEstimator.cpp.o

src/ArBurgEstimator.i: src/ArBurgEstimator.cpp.i
.PHONY : src/ArBurgEstimator.i

# target to preprocess a source file
src/ArBurgEstimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArBurgEstimator.cpp.i
.PHONY : src/ArBurgEstimator.cpp.i

src/ArBurgEstimator.s: src/ArBurgEstimator.cpp.s
.PHONY : src/ArBurgEstimator.s

# target to generate assembly for a file
src/ArBurgEstimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArBurgEstimator.cpp.s
.PHONY : src/ArBurgEstimator.cpp.s

src/ArDurbinEstimator.o: src/ArDurbinEstimator.cpp.o
.PHONY : src/ArDurbinEstimator.o

# target to build an object file
src/ArDurbinEstimator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArDurbinEstimator.cpp.o
.PHONY : src/ArDurbinEstimator.cpp.o

src/ArDurbinEstimator.i: src/ArDurbinEstimator.cpp.i
.PHONY : src/ArDurbinEstimator.i

# target to preprocess a source file
src/ArDurbinEstimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArDurbinEstimator.cpp.i
.PHONY : src/ArDurbinEstimator.cpp.i

src/ArDurbinEstimator.s: src/ArDurbinEstimator.cpp.s
.PHONY : src/ArDurbinEstimator.s

# target to generate assembly for a file
src/ArDurbinEstimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ArDurbinEstimator.cpp.s
.PHONY : src/ArDurbinEstimator.cpp.s

src/Arma2Psd.o: src/Arma2Psd.cpp.o
.PHONY : src/Arma2Psd.o

# target to build an object file
src/Arma2Psd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2Psd.cpp.o
.PHONY : src/Arma2Psd.cpp.o

src/Arma2Psd.i: src/Arma2Psd.cpp.i
.PHONY : src/Arma2Psd.i

# target to preprocess a source file
src/Arma2Psd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2Psd.cpp.i
.PHONY : src/Arma2Psd.cpp.i

src/Arma2Psd.s: src/Arma2Psd.cpp.s
.PHONY : src/Arma2Psd.s

# target to generate assembly for a file
src/Arma2Psd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2Psd.cpp.s
.PHONY : src/Arma2Psd.cpp.s

src/Arma2TF.o: src/Arma2TF.cpp.o
.PHONY : src/Arma2TF.o

# target to build an object file
src/Arma2TF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2TF.cpp.o
.PHONY : src/Arma2TF.cpp.o

src/Arma2TF.i: src/Arma2TF.cpp.i
.PHONY : src/Arma2TF.i

# target to preprocess a source file
src/Arma2TF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2TF.cpp.i
.PHONY : src/Arma2TF.cpp.i

src/Arma2TF.s: src/Arma2TF.cpp.s
.PHONY : src/Arma2TF.s

# target to generate assembly for a file
src/Arma2TF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Arma2TF.cpp.s
.PHONY : src/Arma2TF.cpp.s

src/BLInterpolation.o: src/BLInterpolation.cpp.o
.PHONY : src/BLInterpolation.o

# target to build an object file
src/BLInterpolation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BLInterpolation.cpp.o
.PHONY : src/BLInterpolation.cpp.o

src/BLInterpolation.i: src/BLInterpolation.cpp.i
.PHONY : src/BLInterpolation.i

# target to preprocess a source file
src/BLInterpolation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BLInterpolation.cpp.i
.PHONY : src/BLInterpolation.cpp.i

src/BLInterpolation.s: src/BLInterpolation.cpp.s
.PHONY : src/BLInterpolation.s

# target to generate assembly for a file
src/BLInterpolation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BLInterpolation.cpp.s
.PHONY : src/BLInterpolation.cpp.s

src/BaseWindow.o: src/BaseWindow.cpp.o
.PHONY : src/BaseWindow.o

# target to build an object file
src/BaseWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BaseWindow.cpp.o
.PHONY : src/BaseWindow.cpp.o

src/BaseWindow.i: src/BaseWindow.cpp.i
.PHONY : src/BaseWindow.i

# target to preprocess a source file
src/BaseWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BaseWindow.cpp.i
.PHONY : src/BaseWindow.cpp.i

src/BaseWindow.s: src/BaseWindow.cpp.s
.PHONY : src/BaseWindow.s

# target to generate assembly for a file
src/BaseWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/BaseWindow.cpp.s
.PHONY : src/BaseWindow.cpp.s

src/ButterworthFilter.o: src/ButterworthFilter.cpp.o
.PHONY : src/ButterworthFilter.o

# target to build an object file
src/ButterworthFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ButterworthFilter.cpp.o
.PHONY : src/ButterworthFilter.cpp.o

src/ButterworthFilter.i: src/ButterworthFilter.cpp.i
.PHONY : src/ButterworthFilter.i

# target to preprocess a source file
src/ButterworthFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ButterworthFilter.cpp.i
.PHONY : src/ButterworthFilter.cpp.i

src/ButterworthFilter.s: src/ButterworthFilter.cpp.s
.PHONY : src/ButterworthFilter.s

# target to generate assembly for a file
src/ButterworthFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ButterworthFilter.cpp.s
.PHONY : src/ButterworthFilter.cpp.s

src/Cholesky.o: src/Cholesky.cpp.o
.PHONY : src/Cholesky.o

# target to build an object file
src/Cholesky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Cholesky.cpp.o
.PHONY : src/Cholesky.cpp.o

src/Cholesky.i: src/Cholesky.cpp.i
.PHONY : src/Cholesky.i

# target to preprocess a source file
src/Cholesky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Cholesky.cpp.i
.PHONY : src/Cholesky.cpp.i

src/Cholesky.s: src/Cholesky.cpp.s
.PHONY : src/Cholesky.s

# target to generate assembly for a file
src/Cholesky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Cholesky.cpp.s
.PHONY : src/Cholesky.cpp.s

src/ClusterizedEventFullFeatured.o: src/ClusterizedEventFullFeatured.cpp.o
.PHONY : src/ClusterizedEventFullFeatured.o

# target to build an object file
src/ClusterizedEventFullFeatured.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ClusterizedEventFullFeatured.cpp.o
.PHONY : src/ClusterizedEventFullFeatured.cpp.o

src/ClusterizedEventFullFeatured.i: src/ClusterizedEventFullFeatured.cpp.i
.PHONY : src/ClusterizedEventFullFeatured.i

# target to preprocess a source file
src/ClusterizedEventFullFeatured.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ClusterizedEventFullFeatured.cpp.i
.PHONY : src/ClusterizedEventFullFeatured.cpp.i

src/ClusterizedEventFullFeatured.s: src/ClusterizedEventFullFeatured.cpp.s
.PHONY : src/ClusterizedEventFullFeatured.s

# target to generate assembly for a file
src/ClusterizedEventFullFeatured.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ClusterizedEventFullFeatured.cpp.s
.PHONY : src/ClusterizedEventFullFeatured.cpp.s

src/ComplexFFT.o: src/ComplexFFT.cpp.o
.PHONY : src/ComplexFFT.o

# target to build an object file
src/ComplexFFT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ComplexFFT.cpp.o
.PHONY : src/ComplexFFT.cpp.o

src/ComplexFFT.i: src/ComplexFFT.cpp.i
.PHONY : src/ComplexFFT.i

# target to preprocess a source file
src/ComplexFFT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ComplexFFT.cpp.i
.PHONY : src/ComplexFFT.cpp.i

src/ComplexFFT.s: src/ComplexFFT.cpp.s
.PHONY : src/ComplexFFT.s

# target to generate assembly for a file
src/ComplexFFT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ComplexFFT.cpp.s
.PHONY : src/ComplexFFT.cpp.s

src/CreateDvector.o: src/CreateDvector.cpp.o
.PHONY : src/CreateDvector.o

# target to build an object file
src/CreateDvector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/CreateDvector.cpp.o
.PHONY : src/CreateDvector.cpp.o

src/CreateDvector.i: src/CreateDvector.cpp.i
.PHONY : src/CreateDvector.i

# target to preprocess a source file
src/CreateDvector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/CreateDvector.cpp.i
.PHONY : src/CreateDvector.cpp.i

src/CreateDvector.s: src/CreateDvector.cpp.s
.PHONY : src/CreateDvector.s

# target to generate assembly for a file
src/CreateDvector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/CreateDvector.cpp.s
.PHONY : src/CreateDvector.cpp.s

src/DCT.o: src/DCT.cpp.o
.PHONY : src/DCT.o

# target to build an object file
src/DCT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DCT.cpp.o
.PHONY : src/DCT.cpp.o

src/DCT.i: src/DCT.cpp.i
.PHONY : src/DCT.i

# target to preprocess a source file
src/DCT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DCT.cpp.i
.PHONY : src/DCT.cpp.i

src/DCT.s: src/DCT.cpp.s
.PHONY : src/DCT.s

# target to generate assembly for a file
src/DCT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DCT.cpp.s
.PHONY : src/DCT.cpp.s

src/DST.o: src/DST.cpp.o
.PHONY : src/DST.o

# target to build an object file
src/DST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DST.cpp.o
.PHONY : src/DST.cpp.o

src/DST.i: src/DST.cpp.i
.PHONY : src/DST.i

# target to preprocess a source file
src/DST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DST.cpp.i
.PHONY : src/DST.cpp.i

src/DST.s: src/DST.cpp.s
.PHONY : src/DST.s

# target to generate assembly for a file
src/DST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DST.cpp.s
.PHONY : src/DST.cpp.s

src/DoubleWhitening.o: src/DoubleWhitening.cpp.o
.PHONY : src/DoubleWhitening.o

# target to build an object file
src/DoubleWhitening.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DoubleWhitening.cpp.o
.PHONY : src/DoubleWhitening.cpp.o

src/DoubleWhitening.i: src/DoubleWhitening.cpp.i
.PHONY : src/DoubleWhitening.i

# target to preprocess a source file
src/DoubleWhitening.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DoubleWhitening.cpp.i
.PHONY : src/DoubleWhitening.cpp.i

src/DoubleWhitening.s: src/DoubleWhitening.cpp.s
.PHONY : src/DoubleWhitening.s

# target to generate assembly for a file
src/DoubleWhitening.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/DoubleWhitening.cpp.s
.PHONY : src/DoubleWhitening.cpp.s

src/EventDescription.o: src/EventDescription.cpp.o
.PHONY : src/EventDescription.o

# target to build an object file
src/EventDescription.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventDescription.cpp.o
.PHONY : src/EventDescription.cpp.o

src/EventDescription.i: src/EventDescription.cpp.i
.PHONY : src/EventDescription.i

# target to preprocess a source file
src/EventDescription.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventDescription.cpp.i
.PHONY : src/EventDescription.cpp.i

src/EventDescription.s: src/EventDescription.cpp.s
.PHONY : src/EventDescription.s

# target to generate assembly for a file
src/EventDescription.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventDescription.cpp.s
.PHONY : src/EventDescription.cpp.s

src/EventFullFeatured.o: src/EventFullFeatured.cpp.o
.PHONY : src/EventFullFeatured.o

# target to build an object file
src/EventFullFeatured.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventFullFeatured.cpp.o
.PHONY : src/EventFullFeatured.cpp.o

src/EventFullFeatured.i: src/EventFullFeatured.cpp.i
.PHONY : src/EventFullFeatured.i

# target to preprocess a source file
src/EventFullFeatured.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventFullFeatured.cpp.i
.PHONY : src/EventFullFeatured.cpp.i

src/EventFullFeatured.s: src/EventFullFeatured.cpp.s
.PHONY : src/EventFullFeatured.s

# target to generate assembly for a file
src/EventFullFeatured.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/EventFullFeatured.cpp.s
.PHONY : src/EventFullFeatured.cpp.s

src/FifoBuffer.o: src/FifoBuffer.cpp.o
.PHONY : src/FifoBuffer.o

# target to build an object file
src/FifoBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FifoBuffer.cpp.o
.PHONY : src/FifoBuffer.cpp.o

src/FifoBuffer.i: src/FifoBuffer.cpp.i
.PHONY : src/FifoBuffer.i

# target to preprocess a source file
src/FifoBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FifoBuffer.cpp.i
.PHONY : src/FifoBuffer.cpp.i

src/FifoBuffer.s: src/FifoBuffer.cpp.s
.PHONY : src/FifoBuffer.s

# target to generate assembly for a file
src/FifoBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FifoBuffer.cpp.s
.PHONY : src/FifoBuffer.cpp.s

src/FrameIChannel.o: src/FrameIChannel.cpp.o
.PHONY : src/FrameIChannel.o

# target to build an object file
src/FrameIChannel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIChannel.cpp.o
.PHONY : src/FrameIChannel.cpp.o

src/FrameIChannel.i: src/FrameIChannel.cpp.i
.PHONY : src/FrameIChannel.i

# target to preprocess a source file
src/FrameIChannel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIChannel.cpp.i
.PHONY : src/FrameIChannel.cpp.i

src/FrameIChannel.s: src/FrameIChannel.cpp.s
.PHONY : src/FrameIChannel.s

# target to generate assembly for a file
src/FrameIChannel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIChannel.cpp.s
.PHONY : src/FrameIChannel.cpp.s

src/FrameIStream.o: src/FrameIStream.cpp.o
.PHONY : src/FrameIStream.o

# target to build an object file
src/FrameIStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIStream.cpp.o
.PHONY : src/FrameIStream.cpp.o

src/FrameIStream.i: src/FrameIStream.cpp.i
.PHONY : src/FrameIStream.i

# target to preprocess a source file
src/FrameIStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIStream.cpp.i
.PHONY : src/FrameIStream.cpp.i

src/FrameIStream.s: src/FrameIStream.cpp.s
.PHONY : src/FrameIStream.s

# target to generate assembly for a file
src/FrameIStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/FrameIStream.cpp.s
.PHONY : src/FrameIStream.cpp.s

src/IDCT.o: src/IDCT.cpp.o
.PHONY : src/IDCT.o

# target to build an object file
src/IDCT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/IDCT.cpp.o
.PHONY : src/IDCT.cpp.o

src/IDCT.i: src/IDCT.cpp.i
.PHONY : src/IDCT.i

# target to preprocess a source file
src/IDCT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/IDCT.cpp.i
.PHONY : src/IDCT.cpp.i

src/IDCT.s: src/IDCT.cpp.s
.PHONY : src/IDCT.s

# target to generate assembly for a file
src/IDCT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/IDCT.cpp.s
.PHONY : src/IDCT.cpp.s

src/InverseRealFFT.o: src/InverseRealFFT.cpp.o
.PHONY : src/InverseRealFFT.o

# target to build an object file
src/InverseRealFFT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/InverseRealFFT.cpp.o
.PHONY : src/InverseRealFFT.cpp.o

src/InverseRealFFT.i: src/InverseRealFFT.cpp.i
.PHONY : src/InverseRealFFT.i

# target to preprocess a source file
src/InverseRealFFT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/InverseRealFFT.cpp.i
.PHONY : src/InverseRealFFT.cpp.i

src/InverseRealFFT.s: src/InverseRealFFT.cpp.s
.PHONY : src/InverseRealFFT.s

# target to generate assembly for a file
src/InverseRealFFT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/InverseRealFFT.cpp.s
.PHONY : src/InverseRealFFT.cpp.s

src/LSLLearning.o: src/LSLLearning.cpp.o
.PHONY : src/LSLLearning.o

# target to build an object file
src/LSLLearning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLLearning.cpp.o
.PHONY : src/LSLLearning.cpp.o

src/LSLLearning.i: src/LSLLearning.cpp.i
.PHONY : src/LSLLearning.i

# target to preprocess a source file
src/LSLLearning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLLearning.cpp.i
.PHONY : src/LSLLearning.cpp.i

src/LSLLearning.s: src/LSLLearning.cpp.s
.PHONY : src/LSLLearning.s

# target to generate assembly for a file
src/LSLLearning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLLearning.cpp.s
.PHONY : src/LSLLearning.cpp.s

src/LSLfilter.o: src/LSLfilter.cpp.o
.PHONY : src/LSLfilter.o

# target to build an object file
src/LSLfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLfilter.cpp.o
.PHONY : src/LSLfilter.cpp.o

src/LSLfilter.i: src/LSLfilter.cpp.i
.PHONY : src/LSLfilter.i

# target to preprocess a source file
src/LSLfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLfilter.cpp.i
.PHONY : src/LSLfilter.cpp.i

src/LSLfilter.s: src/LSLfilter.cpp.s
.PHONY : src/LSLfilter.s

# target to generate assembly for a file
src/LSLfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LSLfilter.cpp.s
.PHONY : src/LSLfilter.cpp.s

src/LatticeFilter.o: src/LatticeFilter.cpp.o
.PHONY : src/LatticeFilter.o

# target to build an object file
src/LatticeFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LatticeFilter.cpp.o
.PHONY : src/LatticeFilter.cpp.o

src/LatticeFilter.i: src/LatticeFilter.cpp.i
.PHONY : src/LatticeFilter.i

# target to preprocess a source file
src/LatticeFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LatticeFilter.cpp.i
.PHONY : src/LatticeFilter.cpp.i

src/LatticeFilter.s: src/LatticeFilter.cpp.s
.PHONY : src/LatticeFilter.s

# target to generate assembly for a file
src/LatticeFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LatticeFilter.cpp.s
.PHONY : src/LatticeFilter.cpp.s

src/LeastSquaresLattice.o: src/LeastSquaresLattice.cpp.o
.PHONY : src/LeastSquaresLattice.o

# target to build an object file
src/LeastSquaresLattice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LeastSquaresLattice.cpp.o
.PHONY : src/LeastSquaresLattice.cpp.o

src/LeastSquaresLattice.i: src/LeastSquaresLattice.cpp.i
.PHONY : src/LeastSquaresLattice.i

# target to preprocess a source file
src/LeastSquaresLattice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LeastSquaresLattice.cpp.i
.PHONY : src/LeastSquaresLattice.cpp.i

src/LeastSquaresLattice.s: src/LeastSquaresLattice.cpp.s
.PHONY : src/LeastSquaresLattice.s

# target to generate assembly for a file
src/LeastSquaresLattice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/LeastSquaresLattice.cpp.s
.PHONY : src/LeastSquaresLattice.cpp.s

src/MYWE.o: src/MYWE.cpp.o
.PHONY : src/MYWE.o

# target to build an object file
src/MYWE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/MYWE.cpp.o
.PHONY : src/MYWE.cpp.o

src/MYWE.i: src/MYWE.cpp.i
.PHONY : src/MYWE.i

# target to preprocess a source file
src/MYWE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/MYWE.cpp.i
.PHONY : src/MYWE.cpp.i

src/MYWE.s: src/MYWE.cpp.s
.PHONY : src/MYWE.s

# target to generate assembly for a file
src/MYWE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/MYWE.cpp.s
.PHONY : src/MYWE.cpp.s

src/NotchWidrow.o: src/NotchWidrow.cpp.o
.PHONY : src/NotchWidrow.o

# target to build an object file
src/NotchWidrow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/NotchWidrow.cpp.o
.PHONY : src/NotchWidrow.cpp.o

src/NotchWidrow.i: src/NotchWidrow.cpp.i
.PHONY : src/NotchWidrow.i

# target to preprocess a source file
src/NotchWidrow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/NotchWidrow.cpp.i
.PHONY : src/NotchWidrow.cpp.i

src/NotchWidrow.s: src/NotchWidrow.cpp.s
.PHONY : src/NotchWidrow.s

# target to generate assembly for a file
src/NotchWidrow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/NotchWidrow.cpp.s
.PHONY : src/NotchWidrow.cpp.s

src/Parcor2AR.o: src/Parcor2AR.cpp.o
.PHONY : src/Parcor2AR.o

# target to build an object file
src/Parcor2AR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Parcor2AR.cpp.o
.PHONY : src/Parcor2AR.cpp.o

src/Parcor2AR.i: src/Parcor2AR.cpp.i
.PHONY : src/Parcor2AR.i

# target to preprocess a source file
src/Parcor2AR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Parcor2AR.cpp.i
.PHONY : src/Parcor2AR.cpp.i

src/Parcor2AR.s: src/Parcor2AR.cpp.s
.PHONY : src/Parcor2AR.s

# target to generate assembly for a file
src/Parcor2AR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/Parcor2AR.cpp.s
.PHONY : src/Parcor2AR.cpp.s

src/RLSCanceler.o: src/RLSCanceler.cpp.o
.PHONY : src/RLSCanceler.o

# target to build an object file
src/RLSCanceler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RLSCanceler.cpp.o
.PHONY : src/RLSCanceler.cpp.o

src/RLSCanceler.i: src/RLSCanceler.cpp.i
.PHONY : src/RLSCanceler.i

# target to preprocess a source file
src/RLSCanceler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RLSCanceler.cpp.i
.PHONY : src/RLSCanceler.cpp.i

src/RLSCanceler.s: src/RLSCanceler.cpp.s
.PHONY : src/RLSCanceler.s

# target to generate assembly for a file
src/RLSCanceler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RLSCanceler.cpp.s
.PHONY : src/RLSCanceler.cpp.s

src/RealFFT.o: src/RealFFT.cpp.o
.PHONY : src/RealFFT.o

# target to build an object file
src/RealFFT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RealFFT.cpp.o
.PHONY : src/RealFFT.cpp.o

src/RealFFT.i: src/RealFFT.cpp.i
.PHONY : src/RealFFT.i

# target to preprocess a source file
src/RealFFT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RealFFT.cpp.i
.PHONY : src/RealFFT.cpp.i

src/RealFFT.s: src/RealFFT.cpp.s
.PHONY : src/RealFFT.s

# target to generate assembly for a file
src/RealFFT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/RealFFT.cpp.s
.PHONY : src/RealFFT.cpp.s

src/SelectionOrderCriteria.o: src/SelectionOrderCriteria.cpp.o
.PHONY : src/SelectionOrderCriteria.o

# target to build an object file
src/SelectionOrderCriteria.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/SelectionOrderCriteria.cpp.o
.PHONY : src/SelectionOrderCriteria.cpp.o

src/SelectionOrderCriteria.i: src/SelectionOrderCriteria.cpp.i
.PHONY : src/SelectionOrderCriteria.i

# target to preprocess a source file
src/SelectionOrderCriteria.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/SelectionOrderCriteria.cpp.i
.PHONY : src/SelectionOrderCriteria.cpp.i

src/SelectionOrderCriteria.s: src/SelectionOrderCriteria.cpp.s
.PHONY : src/SelectionOrderCriteria.s

# target to generate assembly for a file
src/SelectionOrderCriteria.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/SelectionOrderCriteria.cpp.s
.PHONY : src/SelectionOrderCriteria.cpp.s

src/VArma2TF.o: src/VArma2TF.cpp.o
.PHONY : src/VArma2TF.o

# target to build an object file
src/VArma2TF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/VArma2TF.cpp.o
.PHONY : src/VArma2TF.cpp.o

src/VArma2TF.i: src/VArma2TF.cpp.i
.PHONY : src/VArma2TF.i

# target to preprocess a source file
src/VArma2TF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/VArma2TF.cpp.i
.PHONY : src/VArma2TF.cpp.i

src/VArma2TF.s: src/VArma2TF.cpp.s
.PHONY : src/VArma2TF.s

# target to generate assembly for a file
src/VArma2TF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/VArma2TF.cpp.s
.PHONY : src/VArma2TF.cpp.s

src/ViewUtil.o: src/ViewUtil.cpp.o
.PHONY : src/ViewUtil.o

# target to build an object file
src/ViewUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ViewUtil.cpp.o
.PHONY : src/ViewUtil.cpp.o

src/ViewUtil.i: src/ViewUtil.cpp.i
.PHONY : src/ViewUtil.i

# target to preprocess a source file
src/ViewUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ViewUtil.cpp.i
.PHONY : src/ViewUtil.cpp.i

src/ViewUtil.s: src/ViewUtil.cpp.s
.PHONY : src/ViewUtil.s

# target to generate assembly for a file
src/ViewUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/ViewUtil.cpp.s
.PHONY : src/ViewUtil.cpp.s

src/WDF2Classify.o: src/WDF2Classify.cpp.o
.PHONY : src/WDF2Classify.o

# target to build an object file
src/WDF2Classify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Classify.cpp.o
.PHONY : src/WDF2Classify.cpp.o

src/WDF2Classify.i: src/WDF2Classify.cpp.i
.PHONY : src/WDF2Classify.i

# target to preprocess a source file
src/WDF2Classify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Classify.cpp.i
.PHONY : src/WDF2Classify.cpp.i

src/WDF2Classify.s: src/WDF2Classify.cpp.s
.PHONY : src/WDF2Classify.s

# target to generate assembly for a file
src/WDF2Classify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Classify.cpp.s
.PHONY : src/WDF2Classify.cpp.s

src/WDF2Reconstruct.o: src/WDF2Reconstruct.cpp.o
.PHONY : src/WDF2Reconstruct.o

# target to build an object file
src/WDF2Reconstruct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Reconstruct.cpp.o
.PHONY : src/WDF2Reconstruct.cpp.o

src/WDF2Reconstruct.i: src/WDF2Reconstruct.cpp.i
.PHONY : src/WDF2Reconstruct.i

# target to preprocess a source file
src/WDF2Reconstruct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Reconstruct.cpp.i
.PHONY : src/WDF2Reconstruct.cpp.i

src/WDF2Reconstruct.s: src/WDF2Reconstruct.cpp.s
.PHONY : src/WDF2Reconstruct.s

# target to generate assembly for a file
src/WDF2Reconstruct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WDF2Reconstruct.cpp.s
.PHONY : src/WDF2Reconstruct.cpp.s

src/WavReconstruction.o: src/WavReconstruction.cpp.o
.PHONY : src/WavReconstruction.o

# target to build an object file
src/WavReconstruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WavReconstruction.cpp.o
.PHONY : src/WavReconstruction.cpp.o

src/WavReconstruction.i: src/WavReconstruction.cpp.i
.PHONY : src/WavReconstruction.i

# target to preprocess a source file
src/WavReconstruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WavReconstruction.cpp.i
.PHONY : src/WavReconstruction.cpp.i

src/WavReconstruction.s: src/WavReconstruction.cpp.s
.PHONY : src/WavReconstruction.s

# target to generate assembly for a file
src/WavReconstruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WavReconstruction.cpp.s
.PHONY : src/WavReconstruction.cpp.s

src/WaveletThreshold.o: src/WaveletThreshold.cpp.o
.PHONY : src/WaveletThreshold.o

# target to build an object file
src/WaveletThreshold.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletThreshold.cpp.o
.PHONY : src/WaveletThreshold.cpp.o

src/WaveletThreshold.i: src/WaveletThreshold.cpp.i
.PHONY : src/WaveletThreshold.i

# target to preprocess a source file
src/WaveletThreshold.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletThreshold.cpp.i
.PHONY : src/WaveletThreshold.cpp.i

src/WaveletThreshold.s: src/WaveletThreshold.cpp.s
.PHONY : src/WaveletThreshold.s

# target to generate assembly for a file
src/WaveletThreshold.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletThreshold.cpp.s
.PHONY : src/WaveletThreshold.cpp.s

src/WaveletTransform.o: src/WaveletTransform.cpp.o
.PHONY : src/WaveletTransform.o

# target to build an object file
src/WaveletTransform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletTransform.cpp.o
.PHONY : src/WaveletTransform.cpp.o

src/WaveletTransform.i: src/WaveletTransform.cpp.i
.PHONY : src/WaveletTransform.i

# target to preprocess a source file
src/WaveletTransform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletTransform.cpp.i
.PHONY : src/WaveletTransform.cpp.i

src/WaveletTransform.s: src/WaveletTransform.cpp.s
.PHONY : src/WaveletTransform.s

# target to generate assembly for a file
src/WaveletTransform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WaveletTransform.cpp.s
.PHONY : src/WaveletTransform.cpp.s

src/WindowFactory.o: src/WindowFactory.cpp.o
.PHONY : src/WindowFactory.o

# target to build an object file
src/WindowFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WindowFactory.cpp.o
.PHONY : src/WindowFactory.cpp.o

src/WindowFactory.i: src/WindowFactory.cpp.i
.PHONY : src/WindowFactory.i

# target to preprocess a source file
src/WindowFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WindowFactory.cpp.i
.PHONY : src/WindowFactory.cpp.i

src/WindowFactory.s: src/WindowFactory.cpp.s
.PHONY : src/WindowFactory.s

# target to generate assembly for a file
src/WindowFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/WindowFactory.cpp.s
.PHONY : src/WindowFactory.cpp.s

src/eternity.o: src/eternity.cpp.o
.PHONY : src/eternity.o

# target to build an object file
src/eternity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/eternity.cpp.o
.PHONY : src/eternity.cpp.o

src/eternity.i: src/eternity.cpp.i
.PHONY : src/eternity.i

# target to preprocess a source file
src/eternity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/eternity.cpp.i
.PHONY : src/eternity.cpp.i

src/eternity.s: src/eternity.cpp.s
.PHONY : src/eternity.s

# target to generate assembly for a file
src/eternity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/eternity.cpp.s
.PHONY : src/eternity.cpp.s

src/fparser.o: src/fparser.cpp.o
.PHONY : src/fparser.o

# target to build an object file
src/fparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fparser.cpp.o
.PHONY : src/fparser.cpp.o

src/fparser.i: src/fparser.cpp.i
.PHONY : src/fparser.i

# target to preprocess a source file
src/fparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fparser.cpp.i
.PHONY : src/fparser.cpp.i

src/fparser.s: src/fparser.cpp.s
.PHONY : src/fparser.s

# target to generate assembly for a file
src/fparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fparser.cpp.s
.PHONY : src/fparser.cpp.s

src/fpoptimizer.o: src/fpoptimizer.cpp.o
.PHONY : src/fpoptimizer.o

# target to build an object file
src/fpoptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fpoptimizer.cpp.o
.PHONY : src/fpoptimizer.cpp.o

src/fpoptimizer.i: src/fpoptimizer.cpp.i
.PHONY : src/fpoptimizer.i

# target to preprocess a source file
src/fpoptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fpoptimizer.cpp.i
.PHONY : src/fpoptimizer.cpp.i

src/fpoptimizer.s: src/fpoptimizer.cpp.s
.PHONY : src/fpoptimizer.s

# target to generate assembly for a file
src/fpoptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/fpoptimizer.cpp.s
.PHONY : src/fpoptimizer.cpp.s

src/tsaLog.o: src/tsaLog.cpp.o
.PHONY : src/tsaLog.o

# target to build an object file
src/tsaLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaLog.cpp.o
.PHONY : src/tsaLog.cpp.o

src/tsaLog.i: src/tsaLog.cpp.i
.PHONY : src/tsaLog.i

# target to preprocess a source file
src/tsaLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaLog.cpp.i
.PHONY : src/tsaLog.cpp.i

src/tsaLog.s: src/tsaLog.cpp.s
.PHONY : src/tsaLog.s

# target to generate assembly for a file
src/tsaLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaLog.cpp.s
.PHONY : src/tsaLog.cpp.s

src/tsaSerialize.o: src/tsaSerialize.cpp.o
.PHONY : src/tsaSerialize.o

# target to build an object file
src/tsaSerialize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaSerialize.cpp.o
.PHONY : src/tsaSerialize.cpp.o

src/tsaSerialize.i: src/tsaSerialize.cpp.i
.PHONY : src/tsaSerialize.i

# target to preprocess a source file
src/tsaSerialize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaSerialize.cpp.i
.PHONY : src/tsaSerialize.cpp.i

src/tsaSerialize.s: src/tsaSerialize.cpp.s
.PHONY : src/tsaSerialize.s

# target to generate assembly for a file
src/tsaSerialize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaSerialize.cpp.s
.PHONY : src/tsaSerialize.cpp.s

src/tsaUtilityFunctions.o: src/tsaUtilityFunctions.cpp.o
.PHONY : src/tsaUtilityFunctions.o

# target to build an object file
src/tsaUtilityFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaUtilityFunctions.cpp.o
.PHONY : src/tsaUtilityFunctions.cpp.o

src/tsaUtilityFunctions.i: src/tsaUtilityFunctions.cpp.i
.PHONY : src/tsaUtilityFunctions.i

# target to preprocess a source file
src/tsaUtilityFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaUtilityFunctions.cpp.i
.PHONY : src/tsaUtilityFunctions.cpp.i

src/tsaUtilityFunctions.s: src/tsaUtilityFunctions.cpp.s
.PHONY : src/tsaUtilityFunctions.s

# target to generate assembly for a file
src/tsaUtilityFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/p4TSA.dir/build.make CMakeFiles/p4TSA.dir/src/tsaUtilityFunctions.cpp.s
.PHONY : src/tsaUtilityFunctions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... p4TSA"
	@echo "... src/AR2.o"
	@echo "... src/AR2.i"
	@echo "... src/AR2.s"
	@echo "... src/AR2Parcor.o"
	@echo "... src/AR2Parcor.i"
	@echo "... src/AR2Parcor.s"
	@echo "... src/ARMAFilter.o"
	@echo "... src/ARMAFilter.i"
	@echo "... src/ARMAFilter.s"
	@echo "... src/ARMAfit.o"
	@echo "... src/ARMAfit.i"
	@echo "... src/ARMAfit.s"
	@echo "... src/ArBurgEstimator.o"
	@echo "... src/ArBurgEstimator.i"
	@echo "... src/ArBurgEstimator.s"
	@echo "... src/ArDurbinEstimator.o"
	@echo "... src/ArDurbinEstimator.i"
	@echo "... src/ArDurbinEstimator.s"
	@echo "... src/Arma2Psd.o"
	@echo "... src/Arma2Psd.i"
	@echo "... src/Arma2Psd.s"
	@echo "... src/Arma2TF.o"
	@echo "... src/Arma2TF.i"
	@echo "... src/Arma2TF.s"
	@echo "... src/BLInterpolation.o"
	@echo "... src/BLInterpolation.i"
	@echo "... src/BLInterpolation.s"
	@echo "... src/BaseWindow.o"
	@echo "... src/BaseWindow.i"
	@echo "... src/BaseWindow.s"
	@echo "... src/ButterworthFilter.o"
	@echo "... src/ButterworthFilter.i"
	@echo "... src/ButterworthFilter.s"
	@echo "... src/Cholesky.o"
	@echo "... src/Cholesky.i"
	@echo "... src/Cholesky.s"
	@echo "... src/ClusterizedEventFullFeatured.o"
	@echo "... src/ClusterizedEventFullFeatured.i"
	@echo "... src/ClusterizedEventFullFeatured.s"
	@echo "... src/ComplexFFT.o"
	@echo "... src/ComplexFFT.i"
	@echo "... src/ComplexFFT.s"
	@echo "... src/CreateDvector.o"
	@echo "... src/CreateDvector.i"
	@echo "... src/CreateDvector.s"
	@echo "... src/DCT.o"
	@echo "... src/DCT.i"
	@echo "... src/DCT.s"
	@echo "... src/DST.o"
	@echo "... src/DST.i"
	@echo "... src/DST.s"
	@echo "... src/DoubleWhitening.o"
	@echo "... src/DoubleWhitening.i"
	@echo "... src/DoubleWhitening.s"
	@echo "... src/EventDescription.o"
	@echo "... src/EventDescription.i"
	@echo "... src/EventDescription.s"
	@echo "... src/EventFullFeatured.o"
	@echo "... src/EventFullFeatured.i"
	@echo "... src/EventFullFeatured.s"
	@echo "... src/FifoBuffer.o"
	@echo "... src/FifoBuffer.i"
	@echo "... src/FifoBuffer.s"
	@echo "... src/FrameIChannel.o"
	@echo "... src/FrameIChannel.i"
	@echo "... src/FrameIChannel.s"
	@echo "... src/FrameIStream.o"
	@echo "... src/FrameIStream.i"
	@echo "... src/FrameIStream.s"
	@echo "... src/IDCT.o"
	@echo "... src/IDCT.i"
	@echo "... src/IDCT.s"
	@echo "... src/InverseRealFFT.o"
	@echo "... src/InverseRealFFT.i"
	@echo "... src/InverseRealFFT.s"
	@echo "... src/LSLLearning.o"
	@echo "... src/LSLLearning.i"
	@echo "... src/LSLLearning.s"
	@echo "... src/LSLfilter.o"
	@echo "... src/LSLfilter.i"
	@echo "... src/LSLfilter.s"
	@echo "... src/LatticeFilter.o"
	@echo "... src/LatticeFilter.i"
	@echo "... src/LatticeFilter.s"
	@echo "... src/LeastSquaresLattice.o"
	@echo "... src/LeastSquaresLattice.i"
	@echo "... src/LeastSquaresLattice.s"
	@echo "... src/MYWE.o"
	@echo "... src/MYWE.i"
	@echo "... src/MYWE.s"
	@echo "... src/NotchWidrow.o"
	@echo "... src/NotchWidrow.i"
	@echo "... src/NotchWidrow.s"
	@echo "... src/Parcor2AR.o"
	@echo "... src/Parcor2AR.i"
	@echo "... src/Parcor2AR.s"
	@echo "... src/RLSCanceler.o"
	@echo "... src/RLSCanceler.i"
	@echo "... src/RLSCanceler.s"
	@echo "... src/RealFFT.o"
	@echo "... src/RealFFT.i"
	@echo "... src/RealFFT.s"
	@echo "... src/SelectionOrderCriteria.o"
	@echo "... src/SelectionOrderCriteria.i"
	@echo "... src/SelectionOrderCriteria.s"
	@echo "... src/VArma2TF.o"
	@echo "... src/VArma2TF.i"
	@echo "... src/VArma2TF.s"
	@echo "... src/ViewUtil.o"
	@echo "... src/ViewUtil.i"
	@echo "... src/ViewUtil.s"
	@echo "... src/WDF2Classify.o"
	@echo "... src/WDF2Classify.i"
	@echo "... src/WDF2Classify.s"
	@echo "... src/WDF2Reconstruct.o"
	@echo "... src/WDF2Reconstruct.i"
	@echo "... src/WDF2Reconstruct.s"
	@echo "... src/WavReconstruction.o"
	@echo "... src/WavReconstruction.i"
	@echo "... src/WavReconstruction.s"
	@echo "... src/WaveletThreshold.o"
	@echo "... src/WaveletThreshold.i"
	@echo "... src/WaveletThreshold.s"
	@echo "... src/WaveletTransform.o"
	@echo "... src/WaveletTransform.i"
	@echo "... src/WaveletTransform.s"
	@echo "... src/WindowFactory.o"
	@echo "... src/WindowFactory.i"
	@echo "... src/WindowFactory.s"
	@echo "... src/eternity.o"
	@echo "... src/eternity.i"
	@echo "... src/eternity.s"
	@echo "... src/fparser.o"
	@echo "... src/fparser.i"
	@echo "... src/fparser.s"
	@echo "... src/fpoptimizer.o"
	@echo "... src/fpoptimizer.i"
	@echo "... src/fpoptimizer.s"
	@echo "... src/tsaLog.o"
	@echo "... src/tsaLog.i"
	@echo "... src/tsaLog.s"
	@echo "... src/tsaSerialize.o"
	@echo "... src/tsaSerialize.i"
	@echo "... src/tsaSerialize.s"
	@echo "... src/tsaUtilityFunctions.o"
	@echo "... src/tsaUtilityFunctions.i"
	@echo "... src/tsaUtilityFunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

