#!/usr/bin/env python3
"""Write src/ExtraWaveletLongTables.inc, the tap tables of the long mothers.

    python tools/generate_long_wavelet_tables.py

The coefficients are PyWavelets' (https://github.com/PyWavelets/pywt, MIT
licence, Copyright (c) 2006-2012 Filip Wasilewski, (c) 2012- The PyWavelets
Developers), taken from the installed package at full double precision and
written with repr(), which round-trips a double exactly.

Convention, the one of ExtraWaveletFamilies.cpp and of GSL's daubechies.c:
h is PyWavelets' rec_lo (its dec_lo reversed) and g[i] = (-1)^i h[nc-1-i],
which is PyWavelets' rec_hi; both checked below, bit for bit.

The script records the PyWavelets version in the file and prints the
orthonormality defect of every table: PyWavelets' own sym16 and sym20 taps are
orthonormal only to about 2e-12 and 1.4e-11 (sum h^2 - 1), and they are kept
as they are, so the tables agree with PyWavelets exactly.
"""
from pathlib import Path

import numpy as np
import pywt

# (C array suffix, PyWavelets name, family, member passed to gsl_wavelet_alloc)
# member: the tap count for Daubechies (GSL's convention), the order for
# Symlets and Coiflets (ExtraWaveletFamilies.cpp's convention).
MOTHERS = [
    ("daub24", "db12", "daubechies", 24),
    ("daub32", "db16", "daubechies", 32),
    ("daub40", "db20", "daubechies", 40),
    ("sym10", "sym10", "symlet", 10),
    ("sym12", "sym12", "symlet", 12),
    ("sym16", "sym16", "symlet", 16),
    ("sym20", "sym20", "symlet", 20),
    ("coif3", "coif3", "coiflet", 3),
    ("coif4", "coif4", "coiflet", 4),
    ("coif5", "coif5", "coiflet", 5),
]

OUT = Path(__file__).resolve().parent.parent / "src" / "ExtraWaveletLongTables.inc"


def table(name, values):
    body = ",\n".join(f"          {v!r}" for v in values)
    return f"        static const double {name}[{len(values)}] = {{\n{body}\n        }};\n"


def main():
    lines = [
        "// Generated by tools/generate_long_wavelet_tables.py -- do not edit by hand.",
        f"// Taps of PyWavelets {pywt.__version__} (MIT licence, Copyright (c) 2006-2012",
        "// Filip Wasilewski, (c) 2012- The PyWavelets Developers): h = rec_lo,",
        "// g = rec_hi = (-1)^i h[nc-1-i], written with repr() (exact doubles).",
        "// Included by ExtraWaveletFamilies.cpp inside its anonymous namespace.",
        "",
    ]
    for suffix, name, family, member in MOTHERS:
        w = pywt.Wavelet(name)
        h = [float(v) for v in w.rec_lo]
        nc = len(h)
        g = [(-1) ** i * h[nc - 1 - i] for i in range(nc)]
        assert h == [float(v) for v in w.dec_lo[::-1]], name
        assert g == [float(v) for v in w.rec_hi], name
        ha = np.array(h)
        defect = max(abs(float(np.dot(ha[2 * m:], ha[:nc - 2 * m])) - (m == 0)) for m in range(nc // 2))
        print(f"{name:6s} {nc:2d} taps, member {member:2d}, offset {nc // 2:2d}, "
              f"max |sum h[k] h[k+2m] - delta_m| = {defect:.2e}")
        lines.append(f"        // ---- {name} (PyWavelets), {nc} taps, member {member} of {family} ----")
        lines.append(table(f"h_{suffix}", h))
        lines.append(table(f"g_{suffix}", g))
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
